image: Previous Visual Studio 2017
clone_folder: C:\TBuild\tdesktop
test: off
deploy: off
configuration: Release

environment:
  matrix:
   - BUILD_VERSION:

matrix:
  fast_finish: true

before_build:
  - .\.appveyor\install.bat

build:
  project: Telegram\Telegram.sln

artifacts:
  - path: out\Release\Telegram.exe
    name: Telegram.exe
